- name: Deploy a web apllication
  hosts: web
  tasks:
  - name: Install all requided dependencies
    apt: name={{ item }} state=installed
    with_items:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip 
